# Trauma - only up to date maps are in the default pool
- type: gameMapPool
  id: DefaultMapPool
  requiredAreas:
  - AreaKitchen # for chef CQC
  - AreaMaints # for ambience and maints spawn rules
  - AreaHallway # for carp migration
  requiredEntities:
  - SpawnPointExtraAiCore # for maps with AI (almost all of them) to work with triumvirate station trait
  - MachineMaterialSilo # for main departments
  - MachineMasterMaterialSilo # for cargo to easily distribute mats to department silos
  maps:
  
  #LOWPOP MAPS 0-30 PLAYERS
  
  - Atlas
  - Amber
  - Cluster
  - Reach
  - Omega
  
  - Bagel
  - Box
  - Fland
  - Marathon
  - Meta
  - Oasis
  - Origin
  - Packed
  - Kettle
  - Leonid
  - Cog
  
  
  #DEROTATED MAPS
  
  #- Loop # needs full area coverage
  #- Saltern # DEATH TO SALTERN
  #- Barratry
  #- Submarine
  #- Delta # decals are overlapping everywhere and have Z fighting
  #- Chloris
  #- Serpentcrest
  #- Nume # slop
  #- Freighter #people hate it
